config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root to: "pages#home"

  get "/profile", to: "pages#profile", as: :profile
  resources :folders
  resources :videos do
    resources :bookmarks, only: [:create]
  end
  resources :bookmarks, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :folder
  belongs_to :video
end

app/models/folder.rb
class Folder < ApplicationRecord
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
  has_many :videos, through: :bookmarks

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :folders
end

app/models/video.rb
class Video < ApplicationRecord
  has_one_attached :video

  belongs_to :user

  validates :name, presence: true
  # validates :description, presence: true
  validates :category, presence: true

  # Here add array of categories
  # validations for size of videos CLOUDINARY (Dimensions and Weigth)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
  
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def create
    @video = Video.find(params[:video_id])
    @folder = Folder.find(params[:bookmark][:folder_id])
    @bookmark = Bookmark.new(video: @video, folder: @folder)
    if @bookmark.save
      redirect_to video_path(@video)
    end
  end

  def destroy
    # @video = Video.find(params[:video_id])
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to folder_path(@bookmark.folder)
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController

  def index
    if current_user
      @favorites_folder = current_user.folders.find_by(name: "Favorites")
      @folders_with_videos = current_user.folders.includes(:videos)
      @folders = current_user.folders.where.not(name: "Favorites").order(created_at: :desc)
      @folder = Folder.new
      @video = Video.new
    else
      redirect_to user_session_path
    end
  end

  def show
    @folder = Folder.find(params[:id])
    @bookmarks = @folder.bookmarks.order(created_at: :desc)
    @bookmark = Bookmark.new
    # @bookmark = Bookmark.find(params[:id])
    # @video = Video.find(params[:id])
    # display all bookmarks from this folder
  end

  def create
    @folder = Folder.new(folder_params)
    @folder.name
    @folder.user = current_user
    if @folder.save
      redirect_to folders_path #notice: "#{@folder.name} was successfully created!"
    end
  end

  def destroy
    @folder = Folder.find(params[:id])
    @folder.destroy
    redirect_to folder_path
  end

  private

  def folder_params
    params.require(:folder).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @bookmark = Bookmark.new
    @videos = Video.all.sample(4)
    @most_searched_videos = Video.where("search_count > 0").order(search_count: :desc).limit(4)
    @most_searched_videos ||= []
    if current_user && current_user.folders.find_by(name: "Favorites").blank?
      Folder.create(name: "Favorites", user_id: current_user.id)
    end
  end

  def profile
    if current_user
      @favorites_folder = current_user.folders.find_by(name: "Favorites")
      @folders_with_videos = current_user.folders.includes(:videos)
      @folders = current_user.folders.where.not(name: "Favorites").order(created_at: :desc)

      @bookmarks_count = 0
      @folders.each do |folder|
        @bookmarks_count += folder.bookmarks.count
      end
      @folder = Folder.new
      @video = Video.new
    else
      redirect_to user_session_path
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def new
    if current_user
      @video = Video.new
      @folders = current_user.folders.where.not(name: "Favorites").order(:name)
    else
      redirect_to user_session_path
    end
  end

  def create
    @video = Video.new(video_params)
    @video.user = current_user
    if @video.save
      folder = Folder.find(@video.category)
      Bookmark.create(folder: folder, video: @video)
      redirect_to folder_path(folder) #notice: "#{@video.name} was successfully uploaded!"
    else
      redirect_to profile_path #alert: "Video upload failed!"
    end
  end

  def show
    @bookmark = Bookmark.new
    @video = Video.find(params[:id])
    @video.increment!(:search_count)
    @related_videos = Video.where(category: @video.category).sample(4)

    if current_user
      @fav_id = current_user.folders.find_by(name: "Favorites").id
      @favorite = Bookmark.where(video: @video).and(Bookmark.where(folder_id: @fav_id))
      @folders = current_user.folders.where.not(name: "Favorites").order(:name)
    end
  end

  def index
    if params[:search]
      @keyword = params[:search].strip
      if @keyword.blank?
        @popular_videos = Video.all.sample(8)
      else
        @results = Video.where("lower(name) like ?", "%#{@keyword.downcase}%")
                   .or(Video.where("lower(category) like ?", "%#{@keyword.downcase}%"))
      end
      if @results.blank?
        @popular_videos = Video.all.sample(4)
      else
        @videos = @results
      end
    end

    @fav_id = Folder.where(name: "Favorites").and(Folder.where(user: current_user))
  end

  private

  def video_params
    params.require(:video).permit(:name, :description, :video, :category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper

  def meta_title
  content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
  content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
  meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
  # little twist to make it work equally with an asset or a url
  meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/folders/index.html.erb
<%= render "shared/navbar" %>

<div class="container" style="padding-top: 90px;">
  <div>
    <h3>My library</h3>
  </div>

  <div style="height: 24px;"></div>

  <%= simple_form_for @folder do |f| %>

  <div class="input-group">
    <%= f.text_field :name, class: "form-control", placeholder: "Add a new folder", style: "outline: none; box-shadow: none;", :autocomplete => :off %>
    <div class="input-group-append">
      <button class="btn btn-primary" type="submit" style="outline: none; box-shadow: none;"><i class="fa-solid fa-folder-plus"></i></button>
    </div>
  </div>

  <% end %>
</div>

<hr>

<div class="container" >
  <div class="row">
    <div class="col-12">
      <div class="input-group">
        <button class="btn btn-outline-primary btn-block dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" style="width: 100%;">Select and view a folder</button>
        <ul class="dropdown-menu" style="width: 100%;">
          <% @folders.each do |folder| %>
            <li><a class="dropdown-item" href="/folders/<%= folder.id %>"><%= folder.name %></a></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<div style="height: 12px;"></div>

<div class="container">
  <div>
    <h4>My folders</h4>
  </div>

  <div style="height: 12px;"></div>

  <div class="folder">
    <% @folders.each do |folder| %>
      <div>
      <%= link_to folder_path(folder) do %>
      <div class="card bg-light">
        <div class="card-body">
          <p><span style="font-weight: 600;"><%= folder.name %></span> (<%= folder.bookmarks.count %>)</p>
          <%= link_to folder_path(folder), data: { turbo_method: :delete } do %>
            <i class="fa-solid fa-trash fa-lg"></i>
          <% end %>
        </div>
      </div>
      <% end %>
      </div>
    <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/folders/show.html.erb
<%= render "shared/navbar" %>

<div class="container" style="padding-top: 90px;">
  <h3><%= @folder.name %></h3>
  <p><i><%= @folder.bookmarks.count %> <% if @folder.bookmarks.count == 1 %>video<% else %>videos<% end %></i></p>
</div>


<% @bookmarks.each do |bookmark| %>
  <hr>

  <div class="container">
    <div class="w-75">
      <h3><%= bookmark.video.name %></h3>
    </div>

    <div style="height: 12px;"></div>

    <div>
      <%= cl_video_tag bookmark.video.video.key, controls: true, class: "card-img-top rounded" %>
    </div>

    <div class="d-flex justify-content-between">
      <div class="d-flex justify-content-start p-2">
        <p><span style="font-weight: 600;">Views:</span>  <%= bookmark.video.search_count %></p>
      </div>
      <div class="d-flex justify-content-end p-2">
        <div data-controller="share" data-share-feedback-text-value="<p style='font-weight: 600; padding: 0; margin: 0;'>Copied</p>">
          <input type="hidden" data-share-target="url" value="<%= cl_video_path bookmark.video.video.key %>">
          <div data-share-target="button" data-action="click->share#copy"><i class="fa-regular fa-copy fa-xl"></i></div>
        </div>
        <div style="width: 12px;"></div>
        <div>
          <%= link_to bookmark_path(bookmark), data: { turbo_method: :delete } do %>
            <i class="fa-solid fa-trash fa-xl"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>

<% end %>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Signary – Your Sign Language Library</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <style>
      body::-webkit-scrollbar {
        display: none;
      }
      input:focus, textarea:focus, select:focus, button:focus {
        outline: none;
        box-shadow: none;
      }
    </style>
    <link href="https://res.cloudinary.com/dq1ieegre/image/upload/v1707917912/favicon_s3oo7m.ico" rel="shortcut icon" type="image/x-icon" />

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container" style="height: 100vh; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/dq1ieegre/image/upload/v1707998058/8A07E870-3448-47B9-9F04-F3B5FF6A3E26_u8keo7.jpg); background-position: center; background-size: cover; background-repeat: no-repeat;">

  <div class="d-flex justify-content-between align-items-center">
    <div class="d-flex justify-content-center align-items-center">
      <div style="color: white;">
        <%= link_to folders_path do %>
          <i class="fa-solid fa-bookmark fa-xl" style="color: white;"></i>
        <% end %>
      </div>
      <div id="logo">&nbsp;&nbsp;signary</div>
    </div>
    <div>
      <%= link_to profile_path do %>
        <i class="fa-solid fa-user fa-xl" style="color: white;"></i>
      <% end %>
    </div>
  </div>

  <div style="height: 120px;"></div>

  <div style="height: 150px;" data-controller="typed">
  </div>

  <div style="height: 150px;"></div>

  <div>
    <div class="mx-auto">
      <form action="/videos">
        <div class="input-group input-group-lg">
          <input type="text" name="search" class="form-control bg-white border-0" style="outline: none; box-shadow: none;" autocomplete="off" placeholder="Search for a sign">
          <button type="submit" class="btn bg-white" style="outline: none; box-shadow: none;"><i class="fa-solid fa-magnifying-glass fa-lg opacity-50"></i></button>
        </div>
      </form>
      <div class="p-2 text-white">
      Examples:&nbsp;&nbsp;<a href="/videos?search=hello" class="text-white opacity-75 px-1">Hello</a>
      <a href="/videos?search=how are you" class="text-white opacity-75 px-1">How are you</a>
      </div>
    </div>
  </div>

  <div style="height: 90px; color: white;" class="d-flex justify-content-center align-items-center">
    <%# <i class="fa-solid fa-hand-point-down fa-xl fa-bounce" style=" --fa-bounce-start-scale-x: 1; --fa-bounce-start-scale-y: 1; --fa-bounce-jump-scale-x: 1; --fa-bounce-jump-scale-y: 1; --fa-bounce-land-scale-x: 1; --fa-bounce-land-scale-y: 1; --fa-bounce-rebound: 0; --fa-animation-iteration-count: 3;"></i> %>
  </div>
</div>

<div style="height: 12px;"></div>

<div class="container">
  <div class="d-flex justify-content-end">
    <button class="btn btn-outline-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Browse by category</button>
    <ul class="dropdown-menu">
      <li><a class="dropdown-item" href="/videos?search=basics">Basics</a></li>
      <li><a class="dropdown-item" href="/videos?search=family">Family</a></li>
      <li><a class="dropdown-item" href="/videos?search=food">Food</a></li>
      <li><a class="dropdown-item" href="/videos?search=greetings">Greetings</a></li>
      <li><a class="dropdown-item" href="/videos?search=phrases">Phrases</a></li>
      <li><a class="dropdown-item" href="/videos?search=sports">Sports</a></li>
      <li><a class="dropdown-item" href="/videos?search=time">Time</a></li>
      <li><a class="dropdown-item" href="/videos?search=work">Work</a></li>
    </ul>
  </div>
</div>

<div style="height: 12px;"></div>

<div class="container">
  <div>
    <h4>Popular signs</h4>
    <div style="height: 12px;"></div>

    <div class="flex">
      <% @videos.each do |video| %>
      <div style="margin-right: 12px;">
        <div class="relative">
          <%= link_to video_path(video) do %>
            <%= cl_video_tag video.video.key, class: "rounded item flex-item" %>
          <% end %>
          <div class="absolute">
          </div>
        </div>
        <div class="d-flex justify-content-start">
          <p style="font-weight: 600;"><%= video.name %></p>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

<hr>

<div class="container">
  <div>
    <h4>Your most viewed signs</h4>
    <div style="height: 12px;"></div>

    <div class="flex">
      <% @most_searched_videos.each do |video| %>
      <div style="margin-right: 12px;">
        <div class="relative">
          <%= link_to video_path(video) do %>
            <%= cl_video_tag video.video.key, class: "rounded item flex-item" %>
          <% end %>
          <div class="absolute">
          </div>
        </div>
        <div class="d-flex justify-content-start">
          <p style="font-weight: 600;"><%= video.name %></p>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

<div style="height: 24px;"></div>

<nav class="container bg-light border-1 border-top">
  <p style="color: primary; padding: 0; margin: 0;">© 2024 Signary, Inc.</p>
</nav>

app/views/pages/profile.html.erb
<%= render "shared/navbar" %>

<div class="container" style="padding-top: 90px;">
  <div class="d-flex justify-content-between">
    <div class="d-flex justify-content-start">
      <div>
        <h3>Hi there&nbsp;&nbsp;<i class="fa-solid fa-hand fa-rotate-by" style="--fa-rotate-angle: 30deg;"></i></h3>
        <div style="height: 6px;"></div>
        <p>You have <span style="font-weight: 600;"><%= @bookmarks_count %> <% if @bookmarks_count == 1 %>video<% else %>videos<% end %></span><br> and <span style="font-weight: 600;"><%= @folders.count %> <% if @folders.count == 1 %>folder<% else %>folders<% end %></span></p>
      </div>
    </div>
    <div class="d-flex justify-content-end align-items-top">
      <%# image_tag "https://media.licdn.com/dms/image/D4E03AQH6RopTGQesqQ/profile-displayphoto-shrink_200_200/0/1708513050927?e=1714003200&v=beta&t=VmtQCjjyw3JAgl0NE0JxZ9vOLyITFRriJgtAtd2N5IE", style: "height: 90px; border-radius: 50%;" %>
    </div>
  </div>
</div>

<hr>

<div class="container">
  <div>
    <h4>Practice your favorites</h4>
    <div style="height: 12px;"></div>

    <div class="flex">
      <% @favorites_folder.videos.each do |video| %>
      <div style="margin-right: 12px;">
        <div>
          <%= link_to video_path(video) do %>
            <%= cl_video_tag video.video.key, class: "rounded item flex-item" %>
          <% end %>
        </div>
        <div class="d-flex justify-content-start">
          <p style="font-weight: 600;"><%= video.name %></p>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/shared/_flashes.html.erb
  <% if notice %>
    <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      <%= alert %>
    </div>
  <% end %>

app/views/shared/_footer.html.erb
<div style="height: 84px;"></div>

<nav class="container bg-primary fixed-bottom">
  <div class="d-flex justify-content-between align-items-center">
    <div>
      <%= link_to root_path do %>
        <i class="fa-solid fa-home fa-xl" style="color: white;"></i>
      <% end %>
    </div>
    <% if current_user %>
      <div>
        <%= link_to folders_path do %>
          <i class="fa-solid fa-bookmark fa-xl" style="color: white;"></i>
        <% end %>
      </div>
      <div>
        <%# link_to new_video_path do %>
          <i class="fa-solid fa-square-plus fa-xl" style="color: white;"></i>
        <%# end %>
      </div>
      <div>
        <%= link_to folder_path(current_user.folders.find_by(name: "Favorites").id) do %>
          <i class="fa-solid fa-heart fa-xl" style="color: white;"></i>
        <% end %>
      </div>
    <% end %>
    <div>
      <% if current_user %>
        <%= link_to destroy_user_session_path, id: "logout", data: { "turbo_method": :delete } do %>
          <i class="fa-solid fa-arrow-right-from-bracket fa-xl" style="color: white;"></i>
        <% end %>
      <% else %>
        <%= link_to profile_path do %>
          <i class="fa-solid fa-user fa-xl" style="color: white;"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_navbar.html.erb
<nav class="container bg-light border-1 border-bottom fixed-top">
  <div class="d-flex justify-content-between align-items-center">
    <div class="flex-grow-1">
    <form action="/videos">
      <div class="input-group">
        <input type="text" name="search" class="form-control bg-white border-1" style="outline: none; box-shadow: none;" placeholder="Search for a sign" autocomplete="off" >
        <button type="submit" class="btn btn-primary"><i class="fa-solid fa-magnifying-glass fa-lg"></i></button>
      </div>
    </form>
    </div>
  </div>
</nav>

<div style="height: 24px;"></div>

app/views/videos/index.html.erb
<%= render "shared/navbar" %>

<% if @videos %>
<div class="container" style="padding-top: 90px;">

  <div>
    <h3>"<%= @keyword.downcase %>"</h3>
    <p><i><%= @videos.count %> <% if @videos.count > 1 %>videos<% else %>video<% end %> found</i></p>
  </div>

  <div style="height: 24px;"></div>

  <div class="video">
    <% @videos.each do |video| %>
      <div>
        <div>
        <%= link_to video_path(video) do %>
          <%= cl_video_tag video.video.key, class: "card-img-top rounded" %>
        <% end %>
        </div>
        <div class="d-flex justify-content-start">
          <p style="font-size: 14px; font-weight: 600;"><%= video.name %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

<% else %>

<div class="container" style="padding-top: 90px;">
  <div>
    <p><i>No results.</i></p>
    <div style="height: 6px;"></div>
    <p><span style="font-weight: 600;">Examples:</span> Hello, How are you, Basics</p>
  </div>
</div>

<hr>

<div class="container">
  <div>
    <h4>Popular signs</h4>
    <div style="height: 12px;"></div>

    <div class="flex">
      <% @popular_videos.each do |video| %>
      <div style="margin-right: 12px;">
        <div>
          <%= link_to video_path(video) do %>
            <%= cl_video_tag video.video.key, class: "rounded item flex-item" %>
          <% end %>
        </div>
        <div class="d-flex justify-content-start">
          <p style="font-weight: 600;"><%= video.name %></p>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

<% end %>

<%= render "shared/footer" %>

app/views/videos/new.html.erb
<%= render "shared/navbar" %>

<div class="container" style="padding-top: 90px;">
  <div>
    <h3>Add a new video</h3>
  </div>

  <div style="height: 24px;"></div>

  <div data-controller="upload" data-upload-change-status-value="<p style='padding: 0; margin: 0;'>Uploading ...</p>">
    <%= simple_form_for @video do |f| %>
      <%= f.text_field :name, class: "form-control", placeholder: "Enter a name", style: "outline: none; box-shadow: none;", :autocomplete => :off %>
      <div style="height: 16px;"></div>
      <%= f.input :category, collection: @folders, prompt: "Select a folder", label: false, input_html: { class: "form-control", style: "outline: none; box-shadow: none;" } %>
      <div class="input-group d-flex justify-content-end">
        <%= f.input :video, as: :file, label: false, input_html: { class: "form-control", style: "outline: none; box-shadow: none;" } %>
        <div class="input-group-append">
          <button class="btn btn-primary" type="submit" data-upload-target="button" data-action="click->upload#busy" style="outline: none; box-shadow: none;"><i class="fa-solid fa-upload"></i></button>
        </div>
      </div>
    <% end %>
  </div>

</div>

<%= render "shared/footer" %>

app/views/videos/show.html.erb
<%= render "shared/navbar" %>

<div class="container" style="padding-top: 90px;">
  <div class="w-75">
    <h3><%= @video.name %></h3>
  </div>

  <div style="height: 12px;"></div>

  <div>
    <%= cl_video_tag @video.video.key, controls: true, class: "card-img-top rounded" %>
  </div>

  <% if current_user %>
    <div class="d-flex justify-content-between py-2">
      <div class="d-flex justify-content-start">
        <%= simple_form_for [@video, @bookmark] do |f| %>
          <div class="input-group" data-controller="bookmark" data-bookmark-change-status-value="<i class='fa-solid fa-spinner'></i>">
            <%= f.association :folder, collection: @folders, class: "form-control", prompt: "Add to a folder", label: false, input_html: { style: "outline: none; box-shadow: none;" } %>
            <div class="input-group-append">
              <button class="btn btn-primary" type="submit" data-bookmark-target="button" data-action="click->bookmark#add"><i class="fa-solid fa-bookmark"></i></button>
            </div>
          </div>
        <% end %>
      </div>
      <div class="d-flex justify-content-end p-2">
        <div data-controller="share" data-share-feedback-text-value="<p style='font-weight: 600; padding: 0; margin: 0;'>Copied</p>">
          <input type="hidden" data-share-target="url" value="<%= cl_video_path @video.video.key %>">
          <div data-share-target="button" data-action="click->share#copy"><i class="fa-regular fa-copy fa-xl"></i></div>
        </div>
        <div style="width: 12px;"></div>
        <div>
          <% if @favorite.blank? %>
          <div>
            <%= simple_form_for [@video, @bookmark] do |f| %>
              <input name="bookmark[folder_id]" id="bookmark_folder_id" type="hidden" value="<%= @fav_id %>">
              <button type="submit" style="background: none; border: 0; padding: 0; margin: 0;"><i class="fa-regular fa-heart fa-xl" style="color: #303030;"></i></button>
            <% end %>
          </div>
          <% else %>
          <div>
            <i class="fa-solid fa-heart fa-xl"></i>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<hr>

<div class="container">
  <div>
    <h4>Related signs</h4>
    <div style="height: 12px;"></div>

    <div class="flex">
      <% @related_videos.each do |video| %>
      <div style="margin-right: 12px;">
        <%= link_to video_path(video) do %>
        <div>
          <%= cl_video_tag video.video.key, class: "rounded item flex-item" %>
        </div>
        <% end %>
        <div class="d-flex justify-content-start">
          <p style="font-weight: 600;"><%= video.name %></p>
        </div>
      </div>
      <% end %>
    </div>
  </div>

</div>

<%= render "shared/footer" %>